"""cw_schemas.runtime — EvaluationResult / RepairPatch / NodeAttempt 主链。

来源：specs/schemas/evaluation_result.md / repair_patch.md / agent_adapter.md §6
"""

from __future__ import annotations

from .actions import (
    RUNTIME_ACTION_SCHEMA_VERSION,
    ArtifactActionRequest,
    ArtifactActionResult,
    RuntimeInstructionAccepted,
    RuntimeInstructionRequest,
)
from .attempt import AdapterError, ArtifactRef, AttemptOutcome, AttemptProvenance, NodeAttempt
from .evaluation import (
    EVALUATION_RESULT_SCHEMA_VERSION,
    ArbitrationOutcome,
    CriterionResult,
    EvalProvenance,
    EvaluationResult,
    EvidenceFeedback,
    FailureDiagnosis,
    Finding,
    JudgeResult,
    RecommendedAction,
    RecommendedActionKind,
)
from .repair import (
    REPAIR_PATCH_SCHEMA_VERSION,
    AddContextRequirementOp,
    AddFewShotExampleOp,
    AddOutputFormatHintOp,
    AddTopicCoverageOp,
    AppendToInstructionsOp,
    AppendToSystemPromptOp,
    AppendToUserPromptTemplateOp,
    BumpPriorityOp,
    BumpTemperatureOp,
    EnableThinkingOp,
    ExtendMaxOutputTokensOp,
    InjectEvidenceLookupToolOp,
    InsertEdgeOp,
    InsertNodeOp,
    MarkConflictResolvedOp,
    Operation,
    PinUpstreamArtifactOp,
    RelaxReviewRuleOp,
    RemoveContextRequirementOp,
    RemoveEdgeOp,
    RemoveNodeOp,
    RepairPatch,
    RepairProvenance,
    ReplaceEvidenceSetOp,
    RequestUserClarificationOp,
    RequestUserDecisionOp,
    RequestUserEditOp,
    RequestUserInputOp,
    ReversalHint,
    SplitNodeOp,
    SummarizeLongFragmentsOp,
    SwitchToModelProfileOp,
    TightenConfidenceThresholdOp,
    TightenConstraintOp,
    TightenRelevanceThresholdOp,
    UpdateContextRequirementOp,
    UpdateNodeOp,
)
from .usage import RunUsage

__all__ = [
    "EVALUATION_RESULT_SCHEMA_VERSION",
    "REPAIR_PATCH_SCHEMA_VERSION",
    "RUNTIME_ACTION_SCHEMA_VERSION",
    "AdapterError",
    "AddContextRequirementOp",
    "AddFewShotExampleOp",
    "AddOutputFormatHintOp",
    "AddTopicCoverageOp",
    "AppendToInstructionsOp",
    "AppendToSystemPromptOp",
    "AppendToUserPromptTemplateOp",
    "ArbitrationOutcome",
    "ArtifactActionRequest",
    "ArtifactActionResult",
    "ArtifactRef",
    "AttemptOutcome",
    "AttemptProvenance",
    "BumpPriorityOp",
    "BumpTemperatureOp",
    "CriterionResult",
    "EnableThinkingOp",
    "EvalProvenance",
    "EvaluationResult",
    "EvidenceFeedback",
    "ExtendMaxOutputTokensOp",
    "FailureDiagnosis",
    "Finding",
    "InjectEvidenceLookupToolOp",
    "InsertEdgeOp",
    "InsertNodeOp",
    "JudgeResult",
    "MarkConflictResolvedOp",
    "NodeAttempt",
    "Operation",
    "PinUpstreamArtifactOp",
    "RecommendedAction",
    "RecommendedActionKind",
    "RelaxReviewRuleOp",
    "RemoveContextRequirementOp",
    "RemoveEdgeOp",
    "RemoveNodeOp",
    "RepairPatch",
    "RepairProvenance",
    "ReplaceEvidenceSetOp",
    "RequestUserClarificationOp",
    "RequestUserDecisionOp",
    "RequestUserEditOp",
    "RequestUserInputOp",
    "ReversalHint",
    "RunUsage",
    "RuntimeInstructionAccepted",
    "RuntimeInstructionRequest",
    "SplitNodeOp",
    "SummarizeLongFragmentsOp",
    "SwitchToModelProfileOp",
    "TightenConfidenceThresholdOp",
    "TightenConstraintOp",
    "TightenRelevanceThresholdOp",
    "UpdateContextRequirementOp",
    "UpdateNodeOp",
]
