"""cw_schemas — CognitiveWorkflow shared Pydantic v2 schemas.

单一真理来源（ADR-0003）：所有 CW 对象的 Pydantic 模型在此定义。
派生的 TS 类型在 `packages/schemas-ts`（@cw/schemas），由 `make codegen` 自动生成。

强约束：
- 仅依赖 pydantic v2
- 禁止依赖 cw_runtime / pydantic-ai / fastapi 等运行时库
- 内部禁止 IO 操作

M1.2 进度（2026-06-15）：
- W1.2.1 ✅ types / ids / metadata
- W1.2.2 ✅ workflow.graph + nodes + policies
- W1.2.3 ✅ contract（NodeContract 6 类）
- W1.2.4 ✅ packs（ContextPack / EvidencePack / ExecutionPack）
- W1.2.5 ✅ runtime（EvaluationResult / RepairPatch / NodeAttempt）
- W1.2.6 ✅ events（StreamEvent — 12 大 category）
"""

from __future__ import annotations

from . import ids, metadata, types
from .contract import (
    ContextRequirement,
    ContextSelector,
    EvaluationContract,
    EvaluationCriterion,
    EvidenceRequirement,
    ExecutionContract,
    ExtraValidatorRef,
    FailCondition,
    HumanDecision,
    HumanGateContract,
    MCPToolRef,
    MemoryContract,
    NodeContract,
    NodeContractBase,
    NodeModelPolicy,
    PassCondition,
    ProjectMemorySelector,
    PromptSection,
    ReferenceSelector,
    RepairContract,
    RepairStrategy,
    RetryPolicy,
    SkillRef,
    StaticTextSelector,
    ToolContract,
    UpstreamArtifactSelector,
    UserInputSelector,
    ValidatorPolicy,
)
from .events import (
    STREAM_EVENT_SCHEMA_VERSION,
    ArtifactEvent,
    ContextEvent,
    ErrorEvent,
    EvaluationEvent,
    HumanEvent,
    LifecycleEvent,
    MetricEvent,
    ModelEvent,
    PlanningEvent,
    RepairEvent,
    StreamEvent,
    StreamEventBase,
    SystemEvent,
    ToolEvent,
    validate_stream_event,
)
from .packs import (
    CONTEXT_PACK_SCHEMA_VERSION,
    EVIDENCE_PACK_SCHEMA_VERSION,
    EXECUTION_PACK_SCHEMA_VERSION,
    CacheMeta,
    Citation,
    CompressionLogEntry,
    CompressionStrategy,
    ContextBudget,
    ContextFragment,
    ContextPack,
    ContextProvenance,
    Evidence,
    EvidenceConflict,
    EvidenceCoverage,
    EvidencePack,
    EvidenceProvenance,
    EvidenceSource,
    ExecutionPack,
    FragmentSource,
    FragmentTransformation,
    OutputFormatHint,
    PromptOverlay,
    RequirementResolution,
    ToolsetSpec,
    UsageLimits,
)
from .runtime import (
    EVALUATION_RESULT_SCHEMA_VERSION,
    REPAIR_PATCH_SCHEMA_VERSION,
    RUNTIME_ACTION_SCHEMA_VERSION,
    AdapterError,
    ArbitrationOutcome,
    ArtifactActionRequest,
    ArtifactActionResult,
    ArtifactRef,
    AttemptOutcome,
    AttemptProvenance,
    CriterionResult,
    EvalProvenance,
    EvaluationResult,
    EvidenceFeedback,
    FailureDiagnosis,
    Finding,
    JudgeResult,
    NodeAttempt,
    Operation,
    RecommendedAction,
    RepairPatch,
    RepairProvenance,
    ReversalHint,
    RuntimeInstructionAccepted,
    RuntimeInstructionRequest,
    RunUsage,
)
from .workflow import (
    ArchiveAction,
    DraftSource,
    EdgeCondition,
    EdgeStyle,
    EndNode,
    EvaluationTaskNode,
    ExecutionPolicy,
    ExecutionTaskNode,
    HumanCheckpointNode,
    HumanDecisionDef,
    MemoryTaskNode,
    NodePosition,
    RepairTaskNode,
    ReviewPolicy,
    StartNode,
    SubflowNode,
    ToolTaskNode,
    WorkflowEdge,
    WorkflowGraph,
    WorkflowModelPolicy,
    WorkflowNode,
)
from .workflow.graph import CURRENT_SCHEMA_VERSION

__version__ = "0.1.0"

# codegen 入口（W1.5.194 完成后共 94 个模型）
__exported_models__: dict[str, type] = {
    # workflow
    "WorkflowGraph": WorkflowGraph,
    "WorkflowEdge": WorkflowEdge,
    "EdgeCondition": EdgeCondition,
    "EdgeStyle": EdgeStyle,
    "DraftSource": DraftSource,
    "ExecutionPolicy": ExecutionPolicy,
    "ReviewPolicy": ReviewPolicy,
    "WorkflowModelPolicy": WorkflowModelPolicy,
    # nodes
    "StartNode": StartNode,
    "EndNode": EndNode,
    "ExecutionTaskNode": ExecutionTaskNode,
    "EvaluationTaskNode": EvaluationTaskNode,
    "RepairTaskNode": RepairTaskNode,
    "HumanCheckpointNode": HumanCheckpointNode,
    "ToolTaskNode": ToolTaskNode,
    "MemoryTaskNode": MemoryTaskNode,
    "SubflowNode": SubflowNode,
    "HumanDecisionDef": HumanDecisionDef,
    "ArchiveAction": ArchiveAction,
    "NodePosition": NodePosition,
    # contract
    "ExecutionContract": ExecutionContract,
    "EvaluationContract": EvaluationContract,
    "RepairContract": RepairContract,
    "HumanGateContract": HumanGateContract,
    "ToolContract": ToolContract,
    "MemoryContract": MemoryContract,
    "PromptSection": PromptSection,
    "ContextRequirement": ContextRequirement,
    "EvidenceRequirement": EvidenceRequirement,
    "EvaluationCriterion": EvaluationCriterion,
    "PassCondition": PassCondition,
    "FailCondition": FailCondition,
    "RepairStrategy": RepairStrategy,
    "HumanDecision": HumanDecision,
    "SkillRef": SkillRef,
    "MCPToolRef": MCPToolRef,
    "ExtraValidatorRef": ExtraValidatorRef,
    "NodeModelPolicy": NodeModelPolicy,
    "RetryPolicy": RetryPolicy,
    "ValidatorPolicy": ValidatorPolicy,
    # packs
    "ContextPack": ContextPack,
    "ContextFragment": ContextFragment,
    "ContextBudget": ContextBudget,
    "CompressionStrategy": CompressionStrategy,
    "CompressionLogEntry": CompressionLogEntry,
    "ContextProvenance": ContextProvenance,
    "CacheMeta": CacheMeta,
    "OutputFormatHint": OutputFormatHint,
    "FragmentTransformation": FragmentTransformation,
    "EvidencePack": EvidencePack,
    "Evidence": Evidence,
    "Citation": Citation,
    "EvidenceCoverage": EvidenceCoverage,
    "EvidenceConflict": EvidenceConflict,
    "RequirementResolution": RequirementResolution,
    "EvidenceProvenance": EvidenceProvenance,
    "ExecutionPack": ExecutionPack,
    "PromptOverlay": PromptOverlay,
    "ToolsetSpec": ToolsetSpec,
    "UsageLimits": UsageLimits,
    # runtime
    "EvaluationResult": EvaluationResult,
    "CriterionResult": CriterionResult,
    "Finding": Finding,
    "FailureDiagnosis": FailureDiagnosis,
    "RecommendedAction": RecommendedAction,
    "ArbitrationOutcome": ArbitrationOutcome,
    "JudgeResult": JudgeResult,
    "EvidenceFeedback": EvidenceFeedback,
    "EvalProvenance": EvalProvenance,
    "RepairPatch": RepairPatch,
    "RepairProvenance": RepairProvenance,
    "ReversalHint": ReversalHint,
    "NodeAttempt": NodeAttempt,
    "AttemptOutcome": AttemptOutcome,
    "AttemptProvenance": AttemptProvenance,
    "AdapterError": AdapterError,
    "ArtifactRef": ArtifactRef,
    "RunUsage": RunUsage,
    "RuntimeInstructionRequest": RuntimeInstructionRequest,
    "RuntimeInstructionAccepted": RuntimeInstructionAccepted,
    "ArtifactActionRequest": ArtifactActionRequest,
    "ArtifactActionResult": ArtifactActionResult,
    # events — 12 envelope（discriminator 由 category 字段，运行时反序列化为对应子类）
    "LifecycleEvent": LifecycleEvent,
    "ModelEvent": ModelEvent,
    "ToolEvent": ToolEvent,
    "EvaluationEvent": EvaluationEvent,
    "RepairEvent": RepairEvent,
    "HumanEvent": HumanEvent,
    "ContextEvent": ContextEvent,
    "PlanningEvent": PlanningEvent,
    "ArtifactEvent": ArtifactEvent,
    "MetricEvent": MetricEvent,
    "ErrorEvent": ErrorEvent,
    "SystemEvent": SystemEvent,
}

__all__ = [
    "CONTEXT_PACK_SCHEMA_VERSION",
    "CURRENT_SCHEMA_VERSION",
    "EVALUATION_RESULT_SCHEMA_VERSION",
    "EVIDENCE_PACK_SCHEMA_VERSION",
    "EXECUTION_PACK_SCHEMA_VERSION",
    "REPAIR_PATCH_SCHEMA_VERSION",
    "RUNTIME_ACTION_SCHEMA_VERSION",
    "STREAM_EVENT_SCHEMA_VERSION",
    "AdapterError",
    "ArbitrationOutcome",
    "ArchiveAction",
    "ArtifactActionRequest",
    "ArtifactActionResult",
    "ArtifactEvent",
    "ArtifactRef",
    "AttemptOutcome",
    "AttemptProvenance",
    "CacheMeta",
    "Citation",
    "CompressionLogEntry",
    "CompressionStrategy",
    "ContextBudget",
    "ContextEvent",
    "ContextFragment",
    "ContextPack",
    "ContextProvenance",
    "ContextRequirement",
    "ContextSelector",
    "CriterionResult",
    "DraftSource",
    "EdgeCondition",
    "EdgeStyle",
    "EndNode",
    "ErrorEvent",
    "EvalProvenance",
    "EvaluationContract",
    "EvaluationCriterion",
    "EvaluationEvent",
    "EvaluationResult",
    "EvaluationTaskNode",
    "Evidence",
    "EvidenceConflict",
    "EvidenceCoverage",
    "EvidenceFeedback",
    "EvidencePack",
    "EvidenceProvenance",
    "EvidenceRequirement",
    "EvidenceSource",
    "ExecutionContract",
    "ExecutionPack",
    "ExecutionPolicy",
    "ExecutionTaskNode",
    "ExtraValidatorRef",
    "FailCondition",
    "FailureDiagnosis",
    "Finding",
    "FragmentSource",
    "FragmentTransformation",
    "HumanCheckpointNode",
    "HumanDecision",
    "HumanDecisionDef",
    "HumanEvent",
    "HumanGateContract",
    "JudgeResult",
    "LifecycleEvent",
    "MCPToolRef",
    "MemoryContract",
    "MemoryTaskNode",
    "MetricEvent",
    "ModelEvent",
    "NodeAttempt",
    "NodeContract",
    "NodeContractBase",
    "NodeModelPolicy",
    "NodePosition",
    "Operation",
    "OutputFormatHint",
    "PassCondition",
    "PlanningEvent",
    "ProjectMemorySelector",
    "PromptOverlay",
    "PromptSection",
    "RecommendedAction",
    "ReferenceSelector",
    "RepairContract",
    "RepairEvent",
    "RepairPatch",
    "RepairProvenance",
    "RepairStrategy",
    "RepairTaskNode",
    "RequirementResolution",
    "RetryPolicy",
    "ReversalHint",
    "ReviewPolicy",
    "RunUsage",
    "RuntimeInstructionAccepted",
    "RuntimeInstructionRequest",
    "SkillRef",
    "StartNode",
    "StaticTextSelector",
    "StreamEvent",
    "StreamEventBase",
    "SubflowNode",
    "SystemEvent",
    "ToolContract",
    "ToolEvent",
    "ToolTaskNode",
    "ToolsetSpec",
    "UpstreamArtifactSelector",
    "UsageLimits",
    "UserInputSelector",
    "ValidatorPolicy",
    "WorkflowEdge",
    "WorkflowGraph",
    "WorkflowModelPolicy",
    "WorkflowNode",
    "__exported_models__",
    "__version__",
    "ids",
    "metadata",
    "types",
    "validate_stream_event",
]
